require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RoomidexRequestsController do

  # This should return the minimal set of attributes required to create a valid
  # RoomidexRequest. As you add validations to RoomidexRequest, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "requester" => "" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RoomidexRequestsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all roomidex_requests as @roomidex_requests" do
      roomidex_request = RoomidexRequest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:roomidex_requests).should eq([roomidex_request])
    end
  end

  describe "GET show" do
    it "assigns the requested roomidex_request as @roomidex_request" do
      roomidex_request = RoomidexRequest.create! valid_attributes
      get :show, {:id => roomidex_request.to_param}, valid_session
      assigns(:roomidex_request).should eq(roomidex_request)
    end
  end

  describe "GET new" do
    it "assigns a new roomidex_request as @roomidex_request" do
      get :new, {}, valid_session
      assigns(:roomidex_request).should be_a_new(RoomidexRequest)
    end
  end

  describe "GET edit" do
    it "assigns the requested roomidex_request as @roomidex_request" do
      roomidex_request = RoomidexRequest.create! valid_attributes
      get :edit, {:id => roomidex_request.to_param}, valid_session
      assigns(:roomidex_request).should eq(roomidex_request)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RoomidexRequest" do
        expect {
          post :create, {:roomidex_request => valid_attributes}, valid_session
        }.to change(RoomidexRequest, :count).by(1)
      end

      it "assigns a newly created roomidex_request as @roomidex_request" do
        post :create, {:roomidex_request => valid_attributes}, valid_session
        assigns(:roomidex_request).should be_a(RoomidexRequest)
        assigns(:roomidex_request).should be_persisted
      end

      it "redirects to the created roomidex_request" do
        post :create, {:roomidex_request => valid_attributes}, valid_session
        response.should redirect_to(RoomidexRequest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved roomidex_request as @roomidex_request" do
        # Trigger the behavior that occurs when invalid params are submitted
        RoomidexRequest.any_instance.stub(:save).and_return(false)
        post :create, {:roomidex_request => { "requester" => "invalid value" }}, valid_session
        assigns(:roomidex_request).should be_a_new(RoomidexRequest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RoomidexRequest.any_instance.stub(:save).and_return(false)
        post :create, {:roomidex_request => { "requester" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested roomidex_request" do
        roomidex_request = RoomidexRequest.create! valid_attributes
        # Assuming there are no other roomidex_requests in the database, this
        # specifies that the RoomidexRequest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RoomidexRequest.any_instance.should_receive(:update).with({ "requester" => "" })
        put :update, {:id => roomidex_request.to_param, :roomidex_request => { "requester" => "" }}, valid_session
      end

      it "assigns the requested roomidex_request as @roomidex_request" do
        roomidex_request = RoomidexRequest.create! valid_attributes
        put :update, {:id => roomidex_request.to_param, :roomidex_request => valid_attributes}, valid_session
        assigns(:roomidex_request).should eq(roomidex_request)
      end

      it "redirects to the roomidex_request" do
        roomidex_request = RoomidexRequest.create! valid_attributes
        put :update, {:id => roomidex_request.to_param, :roomidex_request => valid_attributes}, valid_session
        response.should redirect_to(roomidex_request)
      end
    end

    describe "with invalid params" do
      it "assigns the roomidex_request as @roomidex_request" do
        roomidex_request = RoomidexRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RoomidexRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => roomidex_request.to_param, :roomidex_request => { "requester" => "invalid value" }}, valid_session
        assigns(:roomidex_request).should eq(roomidex_request)
      end

      it "re-renders the 'edit' template" do
        roomidex_request = RoomidexRequest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RoomidexRequest.any_instance.stub(:save).and_return(false)
        put :update, {:id => roomidex_request.to_param, :roomidex_request => { "requester" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested roomidex_request" do
      roomidex_request = RoomidexRequest.create! valid_attributes
      expect {
        delete :destroy, {:id => roomidex_request.to_param}, valid_session
      }.to change(RoomidexRequest, :count).by(-1)
    end

    it "redirects to the roomidex_requests list" do
      roomidex_request = RoomidexRequest.create! valid_attributes
      delete :destroy, {:id => roomidex_request.to_param}, valid_session
      response.should redirect_to(roomidex_requests_url)
    end
  end

end
